spring:
  application:
    name: surveyPlatform
  datasource:
    url: jdbc:mysql://localhost:3306/plat_question?useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root@123456
      database: 5
      timeout: 5000
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  # 添加跨域配置
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  rabbitmq:
    host: localhost  # 服务器地址，本地测试用localhost，生产环境填服务器IP或域名
    port: 5672       # 通信端口，默认5672
    username: guest  # 用户名，本地默认是guest
    password: guest  # 密码，本地默认是guest
    virtual-host: /  # 虚拟主机，默认是/
    # 以下是可选的高级配置
    connection-timeout: 10000  # 连接超时时间，毫秒
    listener:
      simple:
        concurrency: 10  # 消费者最小并发数
        max-concurrency: 50  # 消费者最大并发数
        prefetch: 1  # 每个消费者每次处理的消息数


server:
  port: 8082

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: SurveySystem.entity
  configuration:
    map-underscore-to-camel-case: true
    # 新增：打印SQL语句到控制台
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-scan:
    base-package: SurveySystem.mapper


jwt:
  secret: debiaofan
#  常规两小时
  expiration: 3600
#  记住我 7天
  rememberExpiration: 2592000

role:
  default: 普通用户

#接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: SurveySystem.controller
